import React from "react";
import ReactDom from "react-dom";
// import Counter from "./setStateDemo";
// import Calculate from "./createRefDemo";
// import LifeCycle from "./lifeCycle";
// import Closure from "./closure";
// import Provide from "./designPattern/provider";
// import RenderProps from "./designPattern/renderProps";
// import DomDiff from "./dom-diff";
// import { FunctionComponent, ClassComponent } from "./createComponentDemo";
// import ReducerAndContext from "./designPattern/reducerAndContext";
// import Hook from "./designPattern/hooks";
// import Hoc from "./designPattern/hoc";
// import UseEffect from "./hooks/useEffect";
import Test from "./test/A";
// import ReducerDemo from "./sourceCode/useReducer/index";
ReactDom.render(<Test />, document.getElementById("root"));
